### ISSUE TITLE
Adding a lidar to Leo using hector_models (Hokuyo UTM-30LX)

### ISSUE THREAD

**Issue by tsadarsh** [LeoRover/leo_simulator#2]
ROS: noetic
Ubuntu: 20.04

I am trying to add a Hokuyo Lidar on top of Leo (in simulation) to facilitate SLAM navigation. [Here](https://wiki.ros.org/turtlebot/Tutorials/indigo/Adding%20a%20lidar%20to%20the%20turtlebot%20using%20hector_models%20(Hokuyo%20UTM-30LX)) is the ROS Wiki on **Adding a lidar to the turtlebot using hector_models** that I am following. 
1. I first made new package *add_lidar* and copied all *launch* files from *leo_gazebo* and *leo_viz*, *urdf* files of Leo from *leo_description*, *rviz* files from *leo_viz*.

2. Downloaded *hector_models* package
```sudo apt-get install ros-noetic-hector-models```

3. Added the following line right after the \<robot> tag in *macros.xacro*:
```<xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro"/>```

4. Then added this right before \</robot> tag in *macros.xacro*:
```  
<hokuyo_utm30lx_model name="hokuyo_laser" parent="base_link">
  <origin xyz="0 0 +0.30" rpy="0 0 0" />
</hokuyo_utm30lx_model>
```
5. Then added this code in both *leo_gazebo.launch* and *view_model.launch* (to see in rviz)
```
 <node name="hokuyo" pkg="hokuyo_node" type="hokuyo_node" respawn="false" output="screen">
  <param name="calibrate_time" type="bool" value="true"/>
  <param name="port" type="string" value="/dev/ttyACM0"/>
  <param name="intensity" type="bool" value="false"/>
  <param name="min_ang" value="-2.2689"/>
  <param name="max_ang" value="+2.2689"/>
  <param name="cluster" value="1"/>
  <param name="frame_id" value="hokuyo_laser_frame"/>
 </node>
```

Here now I am facing two problems when launching either *leo_gazebo.launch*(gazebo) or *view_model.launch*(RViz). One, the Lidar model is not present on Leo. Second the *hokuyo_node* fails
![leo_without_lidar](https://user-images.githubusercontent.com/66778010/108582159-62b04400-7357-11eb-94b8-bcf5c0f61a40.png)

> ERROR: cannot launch node of type [hokuyo_node/hokuyo_node]: hokuyo_node

I consider myself a beginner in ROS, so maybe I placed code in wrong places. Please point out where I have gone wrong. [Here is the repository link to *add_lidar_to_LeoRover* package](https://github.com/maddypie/add_lidar_to_LeoRover).

**Comment by bjsowa** [comment]
The tutorial you are referring to may be a little outdated and does not include a simulation (only a real robot), but you generally had a good idea. Here are some things you did wrong:

1. The `macros.xacro` file does not contain the final URDF model, it only defines macros (`leo` and `leo_sim`) that are included in other files. I do not recommend modifying it. Instead, create a new file which will be your main URDF (you can copy the content of `leo_sim.urdf.xacro`) and add your additional links there.
2. The `hokuyo_node` does not have the ability to simulate lidar scans. It can only read data from a real sensor. You won't be able to use it in a simulation.
3. To simulate laser scans in gazebo, you need to define the sensor and the ROS laser plugin in you URDF. Luckily, the [hokuyo_utm30lx.urdf.xacro](https://github.com/tu-darmstadt-ros-pkg/hector_models/blob/melodic-devel/hector_sensors_description/urdf/hokuyo_utm30lx.urdf.xacro) file you are using defines other macros which include the Gazebo sensor description. So, instead of  `hokuyo_utm30lx_model`, just use `hokuyo_utm30lx`. You will also need to define additional parameters for this macro.
4. Since you still need `leo_description` and `leo_gazebo` packages for your simulation to work, you can avoid duplicating files between the packages by defining only what is needed.
5. Newer versions of xacro forbid the usage of macros without the `xacro` keyword, so it should look like this instead: `<xacro:hokuyo_utm30lx/>`

Based on these suggestions, I modified your package and quickly tested if it works:
![Screenshot_20210222_140459](https://user-images.githubusercontent.com/23124539/108717882-16633080-751e-11eb-8fad-d86ba4dfacee.png)

You can download the modified package here:
[add_lidar.zip](https://github.com/LeoRover/leo_simulator/files/6022198/add_lidar.zip)

**Comment by tsadarsh** [comment]
@bjsowa, This brings me much happiness. Thanks a lot for helping me out. I was able to add the Hokuyo Lidar on Leo.

![laser_plugin_success](https://user-images.githubusercontent.com/66778010/108809749-8a114600-75cf-11eb-91fe-2de644cc38d7.png)

I love Leo a lot more now :heart:.

**Comment by bjsowa** [comment]
Glad to hear that :)

Also, one thing worth noticing is that Gazebo has problems rendering shadows with non-NVIDIA GPUs. That is probably the reason why the scene is so dark on your computer. A simple fix is to just disable shadows (On Gazebo GUI, click on `Scene`, then untick `shadows`).

**Comment by tsadarsh** [comment]
> Also, one thing worth noticing is that Gazebo has problems rendering shadows with non-NVIDIA GPUs.

Yes, disabling the *shadows* makes the scene brighter. But I use NVIDIA 1660Ti GPU. This still creates a problem!

**Comment by bjsowa** [comment]
Does your computer perhaps uses hybrid graphics? Could you show the output of this command:
```
glxinfo | grep "OpenGL renderer"
```
If you don't have the `glxinfo` command, install the `mesa-utils` package.

**Comment by bjsowa** [comment]
Also, check the `nvidia-smi` command.

**Comment by tsadarsh** [comment]
> Does your computer perhaps uses hybrid graphics? Could you show the output of this command:
> 
> ```
> glxinfo | grep "OpenGL renderer"
> ```



Output:
> OpenGL renderer string: AMD RENOIR (DRM 3.38.0, 5.8.0-43-generic, LLVM 11.0.0)

And,
> Also, check the `nvidia-smi` command.


I don't have *nvidia-smi* installed, but I found a lot of similar available packages in apt:
>sudo apt install nvidia-utils-435         # version 435.21-0ubuntu7, or
sudo apt install nvidia-utils-440         # version 440.82+really.440.64-0ubuntu6
sudo apt install nvidia-340               # version 340.108-0ubuntu5.20.04.1
sudo apt install nvidia-utils-390         # version 390.141-0ubuntu0.20.04.1
sudo apt install nvidia-utils-450         # version 450.102.04-0ubuntu0.20.04.1
sudo apt install nvidia-utils-450-server  # version 450.102.04-0ubuntu0.20.04.1
sudo apt install nvidia-utils-460         # version 460.32.03-0ubuntu0.20.04.1
sudo apt install nvidia-utils-418-server  # version 418.181.07-0ubuntu0.20.04.1

`nvidia-detector` outputs me **nvidia-driver-460**. That package is 103 MB, should I install it?

**Comment by bjsowa** [comment]
I've always had some problems with hybrid graphics on Ubuntu, so I'm afraid I won't give you a proper advice on what to install. You will have to figure some things yourself.

Maybe this tutorial will help:
https://www.cyberciti.biz/faq/ubuntu-linux-install-nvidia-driver-latest-proprietary-driver/

If everything is properly installed and working, you should be able to switch to the Nvidia card:
```
sudo prime-select nvidia
```

**Comment by tsadarsh** [comment]
> Maybe this tutorial will help:
> https://www.cyberciti.biz/faq/ubuntu-linux-install-nvidia-driver-latest-proprietary-driver/

Yes, I was able to switch over to proprietary `nvidia-driver-460` (restart required) and now the shadows and scene look brighter and better. Thanks once again for your help.

You are kind :smile:.
